import turtle
turtle.shape('turtle')
from math import sin, pi

turtle.up()
turtle.goto(0,-60)
turtle.down()
turtle.color("yellow")
turtle.fill(1)
turtle.circle(60)
turtle.fill(0)
turtle.up()
turtle.goto(25,30)
turtle.down()
turtle.color("blue")
turtle.fill(1)
turtle.circle(5)
turtle.fill(0)
turtle.up()
turtle.goto(-25,30)
turtle.down()
turtle.fill(1)
turtle.circle(5)
turtle.fill(0)
turtle.up()
turtle.goto(0,20)
turtle.down()
turtle.right(90)
turtle.color("black")
turtle.width(6)
turtle.forward(20)
turtle.up()
turtle.goto(30,-20)
turtle.down()
turtle.color("red")
turtle.circle(-30, 180)